
package com.springboot.jaxws.springbootjaxws.service;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.Action;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.3.2
 * Generated source version: 2.2
 * 
 */
@WebService(name = "UnWebService", targetNamespace = "http://service.springbootjaxws.jaxws.springboot.com/")
@XmlSeeAlso({
    ObjectFactory.class
})
public interface UnWebService {


    /**
     * 
     * @param arg1
     * @param arg0
     * @return
     *     returns double
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "suma", targetNamespace = "http://service.springbootjaxws.jaxws.springboot.com/", className = "com.springboot.jaxws.springbootjaxws.service.Suma")
    @ResponseWrapper(localName = "sumaResponse", targetNamespace = "http://service.springbootjaxws.jaxws.springboot.com/", className = "com.springboot.jaxws.springbootjaxws.service.SumaResponse")
    @Action(input = "http://service.springbootjaxws.jaxws.springboot.com/UnWebService/sumaRequest", output = "http://service.springbootjaxws.jaxws.springboot.com/UnWebService/sumaResponse")
    public double suma(
        @WebParam(name = "arg0", targetNamespace = "")
        double arg0,
        @WebParam(name = "arg1", targetNamespace = "")
        double arg1);

}
